on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up TeXLive
      uses: docker://texlive/texlive

    - name: Install Additional Dependencies
      run: tlmgr install vlna

    - name: Build
      run: make

    - name: Clean
      run: make cleanall
